<a href="https://colab.research.google.com/github/mouadjanah-bd/janah-mouad-hammani-ilyass-fin2-tp2/blob/main/janah_mouad_et_ilyass_hammani_fin_2_tp2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd

file_path = '/content/drive/MyDrive/janah mouad et hammani ilyass fin 2 tp 2/extportal.xls'

# Lecture du fichier TSV en sautant les 4 premières lignes pour garder les bons en-têtes de colonnes
try:
    df = pd.read_csv(file_path, sep='\t', skiprows=4)
    print("Le tableau a été chargé avec succès avec les bons en-têtes !")
    display(df.head())
except Exception as e:
    print(f"Erreur lors de la lecture : {e}")

Le tableau a été chargé avec succès avec les bons en-têtes !

,Date,Securities,Nbr 1 Account,Nbr 2 Account,CVA Account,CVA Nbr 2 Account,Total Holdings
0,"September 30, 2026","717,080,499","19,929,540","475,158","7,305,042",0,"744,790,239"
1,"December 31, 2025","724,385,541","19,929,540","475,158",0,0,"744,790,239"
2,"December 31, 2024","724,385,541","557,629,540","475,158",0,0,"1,282,490,239"
3,"December 31, 2023","724,385,541","1,519,729,540","876,477",0,0,"2,244,991,558"
4,"December 31, 2022","724,385,541","1,522,462,451","63,035",0,0,"2,246,911,027"

In [9]:
import sqlite3
import pandas as pd

# Base locale temporaire dans l'environnement Colab
conn = sqlite3.connect('tp_sql.db')

# Importer les données dans la table SQLite "donnees"
df.to_sql('donnees', conn, if_exists='replace', index=False)

# Première requête SQL
requete = '''
SELECT *
FROM donnees
LIMIT 10;
'''
resultat = pd.read_sql_query(requete, conn)
display(resultat)

# Vérifier le nombre de lignes importées
total = pd.read_sql_query(
    'SELECT COUNT(*) AS total FROM donnees;', conn
)
display(total)

conn.close()

,Date,Securities,Nbr 1 Account,Nbr 2 Account,CVA Account,CVA Nbr 2 Account,Total Holdings
0,"September 30, 2026","717,080,499","19,929,540","475,158","7,305,042",0,"744,790,239"
1,"December 31, 2025","724,385,541","19,929,540","475,158",0,0,"744,790,239"
2,"December 31, 2024","724,385,541","557,629,540","475,158",0,0,"1,282,490,239"
3,"December 31, 2023","724,385,541","1,519,729,540","876,477",0,0,"2,244,991,558"
4,"December 31, 2022","724,385,541","1,522,462,451","63,035",0,0,"2,246,911,027"
5,"December 31, 2021","724,385,541","1,522,462,451","67,725",0,0,"2,246,915,717"
6,"December 31, 2020","724,385,541","2,173,462,451","72,644",0,1,"2,897,920,637"
7,"December 31, 2019","732,687,201","14,360,791","74,704",0,0,"747,122,696"
8,"December 31, 2018","732,687,201","14,360,791","79,250",0,0,"747,127,242"
9,"December 31, 2017","732,687,201","14,692,637","2,943",0,0,"747,382,781"

   total
0     43

In [10]:
import sqlite3
import pandas as pd

# Connexion à la base de données
conn = sqlite3.connect('tp_sql.db')

# --- Requête 1 : Calcul de la somme totale et de la moyenne de la colonne 'Total Holdings'
print("=== Requête 1 : Somme globale et Moyenne de 'Total Holdings' ===")
requete_calcul = '''
SELECT
    SUM("Total Holdings") AS Somme_Totale_Holdings,
    AVG("Total Holdings") AS Moyenne_Holdings
FROM donnees;
'''
res_calcul = pd.read_sql_query(requete_calcul, conn)
display(res_calcul)

# --- Requête 2 : Filtrer les dates récentes et afficher la part (calculée) du 'Securities' dans le 'Total Holdings'
print("\n=== Requête 2 : Calcul du pourcentage de 'Securities' par rapport au total pour les années récentes ===")
requete_ratio = '''
SELECT
    Date,
    Securities,
    "Total Holdings",
    (CAST(REPLACE(Securities, ',', '') AS REAL) / CAST(REPLACE("Total Holdings", ',', '') AS REAL)) * 100 AS Pourcentage_Securities
FROM donnees
WHERE Date LIKE '%202%'
LIMIT 5;
'''
res_ratio = pd.read_sql_query(requete_ratio, conn)
display(res_ratio)

# --- Requête 3 : Trier les données pour trouver les 5 dates avec le plus grand 'Nbr 1 Account'
print("\n=== Requête 3 : Top 5 des dates avec le montant le plus élevé dans 'Nbr 1 Account' ===")
requete_top = '''
SELECT
    Date,
    "Nbr 1 Account"
FROM donnees
ORDER BY CAST(REPLACE("Nbr 1 Account", ',', '') AS REAL) DESC
LIMIT 5;
'''
res_top = pd.read_sql_query(requete_top, conn)
display(res_top)

conn.close()

=== Requête 1 : Somme globale et Moyenne de 'Total Holdings' ===

   Somme_Totale_Holdings  Moyenne_Holdings
0                19212.0        446.790698

=== Requête 2 : Calcul du pourcentage de 'Securities' par rapport au total pour les années récentes ===

                 Date   Securities Total Holdings  Pourcentage_Securities
0  September 30, 2026  717,080,499    744,790,239               96.279524
1   December 31, 2025  724,385,541    744,790,239               97.260343
2   December 31, 2024  724,385,541  1,282,490,239               56.482733
3   December 31, 2023  724,385,541  2,244,991,558               32.266738
4   December 31, 2022  724,385,541  2,246,911,027               32.239173

=== Requête 3 : Top 5 des dates avec le montant le plus élevé dans 'Nbr 1 Account' ===

                Date  Nbr 1 Account
0  December 31, 2020  2,173,462,451
1  December 31, 2022  1,522,462,451
2  December 31, 2021  1,522,462,451
3  December 31, 2023  1,519,729,540
4  December 31, 2024    557,629,540